"""Process-name bootstrap for long-running Aura sessions.

Windows console-script launchers generated by pip embed a direct path to
python.exe. That means a long-running Aura process can be caught by broad
commands such as `taskkill /IM python.exe`. This module creates a same-folder
hardlink/copy named aura-runner(.exe) and re-launches Aura through that name.
"""

from __future__ import annotations

import os
import shutil
import sys
import sysconfig
from pathlib import Path


BOOTSTRAP_ENV = "AURA_RUNNER_BOOTSTRAPPED"
FORCE_BOOTSTRAP_ENV = "AURA_RUNNER_BOOTSTRAP_FORCE"
RUNNER_BASENAME = "aura-runner"


def runner_path_for(executable: str | os.PathLike[str]) -> Path:
    """Return the runner path beside the given Python executable."""
    exe = Path(executable)
    suffix = ".exe" if exe.suffix.lower() == ".exe" else ""
    return exe.with_name(f"{RUNNER_BASENAME}{suffix}")


def _is_python_named_executable(executable: str | os.PathLike[str]) -> bool:
    name = Path(executable).name.lower()
    if name in {"python.exe", "pythonw.exe", "python"}:
        return True
    if name.startswith("python") and name.endswith(".exe"):
        return True
    tail = name.removeprefix("python")
    if tail and all(part.isdigit() for part in tail.split(".") if part):
        return True
    return False


def _looks_like_aura_invocation(argv0: str | os.PathLike[str]) -> bool:
    path = Path(argv0)
    name = path.name.lower()
    if name in {"aura", "aura.exe", "aura-script.py", "aura-script.pyw"}:
        return True
    if name == "main.py" and path.parent.name == "orchestrator":
        return True
    return False


def _runner_matches_source(source: Path, runner: Path) -> bool:
    try:
        source_stat = source.stat()
        runner_stat = runner.stat()
    except OSError:
        return False
    if os.path.normcase(str(source)) == os.path.normcase(str(runner)):
        return True
    if source_stat.st_size != runner_stat.st_size:
        return False
    if int(source_stat.st_mtime) != int(runner_stat.st_mtime):
        return False
    return True


def ensure_runner_executable(
    executable: str | os.PathLike[str] | None = None,
    *,
    force: bool = False,
) -> Path:
    """Create aura-runner beside the current interpreter.

    Prefer a hardlink so the runner stays tied to the exact interpreter image.
    If hardlink creation is unavailable, fall back to copying the executable.
    """
    source = Path(executable or sys.executable).resolve()
    runner = runner_path_for(source)
    if not force and _runner_matches_source(source, runner):
        return runner

    runner.parent.mkdir(parents=True, exist_ok=True)
    tmp = runner.with_name(f"{runner.name}.tmp-{os.getpid()}")
    try:
        if tmp.exists():
            tmp.unlink()
        if force and runner.exists():
            runner.unlink()
        try:
            os.link(source, tmp)
        except OSError:
            shutil.copy2(source, tmp)
        os.replace(tmp, runner)
    except OSError:
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:
                pass
        if runner.exists():
            return runner
        raise

    return runner


def patch_console_launcher(
    launcher: str | os.PathLike[str],
    runner: str | os.PathLike[str],
) -> bool:
    """Patch a distlib/setuptools Windows launcher to use aura-runner.

    The generated launcher stores its target interpreter in a trailing shebang
    line such as `#!C:\\Python\\python.exe`. Replacing that line keeps the
    command name `aura` unchanged while making the long-running interpreter
    process appear as aura-runner.exe.
    """
    launcher_path = Path(launcher)
    runner_path = Path(runner)
    data = launcher_path.read_bytes()
    marker = b"#!"
    start = data.rfind(marker)
    if start < 0:
        return False
    end = data.find(b"\n", start)
    if end < 0:
        return False

    target = f"#!{runner_path}\n".encode()
    old_line = data[start : end + 1]
    if old_line == target:
        return False

    patched = data[:start] + target + data[end + 1 :]
    tmp = launcher_path.with_name(f"{launcher_path.name}.tmp-{os.getpid()}")
    try:
        tmp.write_bytes(patched)
        os.replace(tmp, launcher_path)
    except OSError:
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:
                pass
        raise
    return True


def _candidate_aura_launchers() -> list[Path]:
    candidates: list[Path] = []
    scripts = sysconfig.get_path("scripts")
    if scripts:
        candidates.append(Path(scripts) / ("aura.exe" if os.name == "nt" else "aura"))
    found = shutil.which("aura")
    if found:
        candidates.append(Path(found))
    if _looks_like_aura_invocation(sys.argv[0]):
        candidates.append(Path(sys.argv[0]))

    unique: list[Path] = []
    seen: set[str] = set()
    for path in candidates:
        key = os.path.normcase(os.path.abspath(os.fspath(path)))
        if key in seen:
            continue
        seen.add(key)
        unique.append(path)
    return unique


def install_runner_for_current_environment(*, force: bool = True) -> dict[str, object]:
    """Ensure aura-runner exists and patch current-env aura launcher if possible."""
    runner = ensure_runner_executable(force=force)
    patched: list[str] = []
    failed: list[str] = []

    if os.name == "nt":
        for launcher in _candidate_aura_launchers():
            if not launcher.exists() or launcher.suffix.lower() != ".exe":
                continue
            try:
                if patch_console_launcher(launcher, runner):
                    patched.append(str(launcher))
            except OSError as exc:
                failed.append(f"{launcher}: {exc}")

    return {
        "runner": str(runner),
        "patched": patched,
        "failed": failed,
    }


def should_reexec_with_runner(
    executable: str | os.PathLike[str] | None = None,
    environ: dict[str, str] | None = None,
    argv0: str | os.PathLike[str] | None = None,
) -> bool:
    env = environ or os.environ
    if env.get(BOOTSTRAP_ENV) == "1":
        return False
    if env.get(FORCE_BOOTSTRAP_ENV) != "1" and not _looks_like_aura_invocation(argv0 or sys.argv[0]):
        return False
    exe = executable or sys.executable
    name = Path(exe).name.lower()
    if name.startswith(RUNNER_BASENAME):
        return False
    return _is_python_named_executable(exe)


def maybe_reexec_with_runner() -> None:
    """Re-launch Aura under aura-runner if the process is still python(.exe)."""
    if not should_reexec_with_runner():
        return

    try:
        result = install_runner_for_current_environment()
        runner = Path(str(result["runner"]))
    except OSError as exc:
        print(
            f"[WARN] Could not create aura-runner next to {sys.executable}: {exc}. "
            "Continuing under the current Python executable.",
            file=sys.stderr,
        )
        return

    if os.name == "nt":
        # Windows does not provide a reliable POSIX-style exec replacement for
        # this handoff. The patched launcher makes future `aura` invocations run
        # under aura-runner.exe directly; keep this first invocation alive.
        return

    env = os.environ.copy()
    env[BOOTSTRAP_ENV] = "1"
    env["AURA_RUNNER_SOURCE_PYTHON"] = sys.executable
    args = [str(runner), "-m", "orchestrator.main", *sys.argv[1:]]
    os.execve(str(runner), args, env)


def main() -> int:
    """Install/repair the runner for the active Python environment."""
    try:
        result = install_runner_for_current_environment()
    except OSError as exc:
        print(f"[ERROR] Could not install aura-runner: {exc}", file=sys.stderr)
        return 1

    print(f"[OK] aura-runner: {result['runner']}")
    patched = result.get("patched") or []
    failed = result.get("failed") or []
    for path in patched:
        print(f"[OK] patched launcher: {path}")
    for item in failed:
        print(f"[WARN] launcher patch failed: {item}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
